### PR TITLE
1.9 and lore on plants

### PR DESCRIPTION
**Pull request by TealNerd**
@ProgrammerDan

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Oh wow I forgot about this, yet was just thinking conceptually about this last night.

Can you update and reopen against the Devoted repo?

**Comment by TealNerd** [comment]
i was actually thinking about rewriting the plugin entirely

**Comment by ProgrammerDan** [comment]
should I message you a conservative wishlist?

**Comment by TealNerd** [comment]
yeah go for it

personally my plan is to go for persistent growth but short grow times and lenient-ness (what are words even) because if crops aren't being used for xp directly there's no reason to very harshly limit their grow times/location. That said I'd be happy to make it super configurable :)

**Comment by ProgrammerDan** [comment]
yeah it's useless unless its configurable, but if you've already got the logic to manipulate and control growth times then it's basically configurable by definition :P

**Pull request closed without merging**
