### PR TITLE
Fix big trees

### LINKED ISSUE #61: Oak trees bug
I already brought this up a while ago on the forum, but it seems like it got lost. Oak trees can grow in just a few minutes, it doesn't seem like their growth events are cancelled at all, I was not able to observe the same behavior for other trees. 
They still grow persistent and I've had cases, where I removed saplings, but the tree grew later anyway at the same spot.

@gipsy-king

### PR DESCRIPTION
**Pull request by gipsy-king**
fix BIG_TREE/large oaks growing at vanilla rates, and some minor cleanups.

closes #61

### CODE REVIEW

**Comment by ttk2** [comment]
merging

**Comment by ttk2** [comment]
so is this a jar or a config update?

**Comment by gipsy-king** [comment]
both

**Comment by ttk2** [comment]
ok finally putting this online.

**Pull request merged**
