### PR TITLE
Making redwood grow in Ice plains and Ice mountains

### PR DESCRIPTION
**Pull request by Maxopoly**
Someone asked for it and it kind of makes sense, so I thought why not.

### CODE REVIEW

**Comment by gipsy-king** [comment]
I would leave `cold_forest` as it is, and add `cold` with 0.75 or similar. There are oak and spruce in vanilla ice biomes, but only a few scattered around, unlike taiga which is full of them.

**Comment by Maxopoly** [comment]
But "cold_forest" contains Taiga and Taiga Hills and so does "cold", which one would be used.

**Comment by gipsy-king** [comment]
I would guess that `taiga` would apply from `cold_forest` which comes first: https://github.com/Maxopoly/RealisticBiomes/blob/master/src/com/untamedears/realisticbiomes/GrowthConfig.java#L217

**Comment by Maxopoly** [comment]
Wouldn't it be the one put into the biomeMultipliers hashmap second? The second put just overwrites what was in there before.

**Comment by gipsy-king** [comment]
Yeah the order would have to be

    cold: 0.75
    cold_forest: 2.0

So that `cold_forest` only overwrite the values for tiaga in the map.

**Comment by Maxopoly** [comment]
Like this?

**Comment by gipsy-king** [comment]
I'm 99% sure that would work, if you didn't make a test post for getRate rewrite we should merge this and test it all in one run.

**Comment by gipsy-king** [comment]
Not that anybody will test it but it's an excuse if it fails later on the main.

**Comment by Maxopoly** [comment]
Yeah, I'll put it all in a post later

**Pull request merged**
