### PR TITLE
Set growth time to 12hrs for cactus and sugarcane

### PR DESCRIPTION
**Pull request by gipsy-king**
Yes this is increases the growth times 24 times longer than current
setting. A block from these plants will take 12hrs to grow. This is
to deter players from botting these kind of farms, which right now
is still more efficient, and defeats the purpose of persistence.

If you feel this imbalances XP recipes, go ahead and make a PR to
change the recipes, once this goes live.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
It's not really a "you feel this imbalances" -- it categorically does. @Goldmattress took ideal growth + farm design into account when balancing the recipes. This dramatic a change ...

Does Cactus really cause that much of an issue? Once water is "fully flowing" it doesn't reflow, meaning there is no additional compute cost there. The only "expensive" part of a cactus farm is the collection area, which should be a single hopper feeding into a collection tower. The collection tower is literally the "laggiest" part of the whole design, but likely tops out at 30-40 hoppers. 

That's not going to cause much lag. Keeping the 81 chunks around the player loaded will cause some lag, sure, because of the greater number of random BUD events that the server must manage. 

Would it be possible to decrease the % chance of cactus growth if the chunk is loaded? E.g. motivate unloading the chunk as keeping it unloaded makes it "more" productive that keeping it loaded? That would make way more sense then simply increasing the time to grow by 24x.

**Comment by gipsy-king** [comment]
Yes it completely screws with balance, but I am only saying that *I* am not providing a matching XP rebalancing PR, someone else would have to do that. I am only concerned to remove the need for AFKing cactus.

AFKing cactus farms must be a cause of lag, otherwise why are we generally after hoppers, things that tick in general, and AFKers?

Decreasing cactus growth does not make much sense, because it penalizes cactus farms near players.

**Comment by ProgrammerDan** [comment]
Note: moving my comments to the forum, didn't realize you'd started one there :)

**Comment by Goldmattress** [comment]
The idea that increasing the growth times removes the need to afk any more
than a 3h one is patently absurd, i will discuss this further when i get
home

I will rebalance shit to be far slower then and adjust xp then.

**Comment by gipsy-king** [comment]
Closing after forum discussion, will make a new PR with cactus, sugarcane, melons, pumpkins all set to about 24h. That way XP can be rebalanced at once.

**Pull request closed without merging**
