### PR TITLE
Rabbits are crepuscular and live everywhere!

### PR DESCRIPTION
**Pull request by ribagi**
Rabbits live everywhere from the Mojave desert, to forests in Indonesia, to Appalachian Mountains, and to Sweden. Plus they are rabbits, they breed like rabbits.

### CODE REVIEW

**Comment by rourke750** [comment]
@ttk2

**Comment by ttk2** [comment]
so the proposal is to expand the range of rabbits and that the existing
settings are too restrictive.

**Comment by WildWeazel** [comment]
specifically, to make them breed 100% everywhere effectively exempt from RB

**Comment by rourke750** [comment]
bump

**Comment by ttk2** [comment]
I don't see pro's or con's at all either way.

**Comment by ribagi** [comment]
With my Xp pull on Factory mod, we should also do basically the same to all animals and go more hitler on mustercull.

**Comment by ttk2** [comment]
Why?

**Comment by ribagi** [comment]
Because there is no longer any balance issues with having cows, chickens, and sheep raised in any biome with Matta's and mine's xp stuff.

**Comment by ttk2** [comment]
why is that? Just no meat in recepies?

**Comment by gipsy-king** [comment]
must be declared as entity_RABBIT becuase for some reason there's a Material.RABBIT in bukkit. I can include that while doing tree persistence and could also change the biomes as proposed. except water, it makes no sense to spawn rabbits in water biome @ribagi ?

**Comment by gipsy-king** [comment]
@ribagi this can be rebased now that my merge is done which fixes rabbits in the config.

But do we really want to allow rabbits to breed anywhere at full rate? In ocean too??? IMO this goes against the purpose of RB and civcraft's scarcity in general.

**Comment by WildWeazel** [comment]
Rabbits breeding in the End? Has science gone too far???

**Pull request closed without merging**
