### PR TITLE
Reduced growth speeds

### PR DESCRIPTION
**Pull request by Goldmattress**
Reduced growth speeds for Melons, Pumpkins, Cacti and Sugar cane to 12h

### CODE REVIEW

**Comment by gipsy-king** [comment]
Let me check quickly because I think that sugarcanes and cactus' time are for both blocks so you'd want double time for those.

**Comment by Goldmattress** [comment]
So it adds 2 blocks on top when the effect kicks in?

**Comment by gipsy-king** [comment]
It adds one in half time, then the another when time is up. Checking right now.

**Comment by gipsy-king** [comment]
No I was wrong, they grow straight to 3 blocks when time is up, ignore what I said.

**Comment by Goldmattress** [comment]
So adjust or not?

**Comment by gipsy-king** [comment]
No, it's good.

**Comment by ProgrammerDan** [comment]
commits are good from a yaml perspective

**Comment by gipsy-king** [comment]
@ttk2 this should reduce AFKing at least of fully-auto farms significantly.

**Comment by ttk2** [comment]
Cool. What about the xp rebalance?

**Comment by gipsy-king** [comment]
@ttk2 https://github.com/Civcraft/FactoryMod/pull/135

**Comment by ttk2** [comment]
nice, going online tuesday when I can oversee it.

**Pull request merged**
