### PR TITLE
Added support for custom trees

### PR DESCRIPTION
**Pull request by TealNerd**

### CODE REVIEW

**Comment by Maxopoly** [comment]
This is pretty awesome. Multiple things though:

Could you hide the MultiBlockStructure behind an interface, so we could easily add support for other formats (mainly .schematic) later on?

Also could you change the methods to load and check for space so you can give them a list of acceptable blocks/materials (like leaves in vanilla) that wont be overwritten or are accepable space additionally to air?


Thanks for making this

**Comment by ProgrammerDan** [comment]
Cool. Can you provide some examples of MBT's? How can they be controlled in the config (selectivity of species, type, binding to a configuration of saplings, etc.)?

**Comment by TealNerd** [comment]
@ProgrammerDan im making it a little better so you'll specify which trees are overriden in the config. and in the future maybe support for custom sapling arrangements (although that would require a bunch more work and changes and stuff)

**Comment by Maxopoly** [comment]
Ok looks cool, I'd say we merge it. Do you want to make actual functionality with it (tying it to lored saplings or whatever) yourself?

**Comment by TealNerd** [comment]
i can add that pretty easily if you want

**Comment by Maxopoly** [comment]
Yeah that would be nice. Honestly I dont even know yet how we want that whole thing to work, whether those custom trees should drop custom sapling or whether any sapling dropped should have a chance to be a custom sapling or whether any normal tree may grow into a custom tree or whether custom trees only grow from custom saplings from factories. etc.

You' re pretty much free to do whatever you want with that.

**Comment by ProgrammerDan** [comment]
I'd recommend just leaving it up to the config. Add an indication to the growth config for each major tree type of which custom trees could spawn from it; and add a new section that specifies a custom tree type and what lore on a sapling will "initiate" its growth.

**Comment by TealNerd** [comment]
do we have something in civmodcore to store lore on blocks or do i need to add that to rb?

**Comment by ProgrammerDan** [comment]
In my head at least I figured you could just capture the lore on blockplace, and alter the type of entry in the biome growth table as a form of storage.

**Comment by TealNerd** [comment]
oh yeah that could work

**Comment by Crushtoe** [comment]
Would it return the sapling with lore if you broke it again?

**Comment by Maxopoly** [comment]
It wouldn't, but we could make it so that it does.

**Comment by ProgrammerDan** [comment]
@TealNerd prettymuch as soon as those config / placement options are done I think this is a great merge. Thanks!

**Comment by ProgrammerDan** [comment]
Oh last thing if you haven't already please rebase against v1.9 branch

**Pull request closed without merging**
