### PR TITLE
Balanced presistent blocks

### PR DESCRIPTION
**Pull request by Goldmattress**
Balanced presistent blocks to be the same as old growth rates

### CODE REVIEW

**Comment by rourke750** [comment]
@ttk2

**Comment by ttk2** [comment]
what are they now less or more? Assuming 24 hour idling.

**Comment by gipsy-king** [comment]
my reasoning for 3hrs was that crops take a bit over 30min in vanilla, but are set to 6hrs on civcraft. I roughly applied that logic to the new persistent crops.

**Comment by dbear20** [comment]
This would roughly double the non persitent rates according to the numbers in [this](https://www.reddit.com/r/Civcraft/comments/3d1m83/anyone_else_noticed_the_complete_decrease_in_afk/) post.

**Comment by gipsy-king** [comment]
I also just remembered that farms of these newly persistent crops won't immediately be persistent: each crop/fruit block has to grow naturally once before it is made persistent. This might lead to reports that are too low initially.

**Comment by Goldmattress** [comment]
Gipsy king is wrong they are set at 20min in civcraft, they take 4 min in vanilla

**Comment by ttk2** [comment]
minutes to grow?

**Comment by Goldmattress** [comment]
yes, it's semi random, but the 50% grown is at about 4min.

**Comment by gipsy-king** [comment]
@Goldmattress are you sure? On [minecraft wiki](http://minecraft.gamepedia.com/Tutorials/Crop_farming#Growth_rate) its says

> Most (4/5) planted crops will reach maturity within 37 minutes (about 2 minecraft days).

Regardless of actual vanilla growth times, I guess that the reason you want to keep cactus/sugarcane/melon/pumkin growth times unchanged is that XP recipes are balanced by those growth times?

**Comment by Goldmattress** [comment]
80% is not the average, 50% is. http://minecraft.gamepedia.com/File:MCWheatGrowth.jpg

I am unsure if the "full grown" one is what counts or stage one is the one that counts, from personal experience and what I can find of numbers on the respective wiki pages for the plants I'm going with stage 1 growth and assuming that full grown refers to the final stage of the wheat plant.

**Comment by gipsy-king** [comment]
The green line is what counts regarding RB crop growth time. It should take from 30min (60% probability) to 40min (85% probability) or up to 50min (near 100% prob) more to have fully grown. So the average time of 37min stated on the wiki seems pretty accurate.

On civcraft, wheat takes **1 hour** under optimal conditions, with 4 clay block as soil, for reference to vanilla times.

In this case, since none of these new crops have soil blocks that can boost their time, their growth time should be set to exactly what we want. Previously without persistence, **was 30 minutes the average time for all of cactus, sugarcane, melons and pumpkins?**

Also, cactus and sugarcane times are for *the two top blocks*, not just a single block of growth, i.e. **one cactus/sugarcane blocks grows in half the time of `persistent_growth_period`**.

**Comment by gipsy-king** [comment]
Re: cactus/sugarcane growth time, in other words the `persistent_growth_period` is for growing a single cactus block into a 3 cactus column of blocks, that's why one cactus block effectively grows in half that time.

**Comment by Goldmattress** [comment]
The green line is the aggregate of all the stages, these stages are not
relevant to columnar or stalk pants aas they only have 1 stage.

As I have said before the average times before was around 20min, 4min/0.2.
This lines up with yields from farms I have used, about 1 DC an hour or so
for a 9x9 chunk cacti farm, versus the other assumption which is 6 stacks.

I've gotten 6 stacks in the time it took me to empty all my reserve chests,
about 5-10min.

**Comment by gipsy-king** [comment]
Ah I get it, so cactus/melon should grow like the *first* stage of crops.

So it should be about 1/6th of crops, which is 3, **so 0.5 seems right** @dbear20 @ttk2 . Thanks for clearing that up!

**Comment by ttk2** [comment]
we can go with it for now then. I would like to get harvest times down to a couple of times a day so people don't need to idle and harvest every x minutes. but that's a later discussion.

**Pull request merged**
