### PR TITLE
Reset growth for column-type plants in BlockBreakEvents

### PR DESCRIPTION
**Pull request by BlackXnt**
#87

### CODE REVIEW

**Comment by gipsy-king** [comment]
Looks good to me 👍

**Comment by ProgrammerDan** [comment]
Pattern is strange to do if ..return when if...else would do, but besides that style issue this seems fine.

**Comment by ProgrammerDan** [comment]
Any concerns @mgrandi or @Maxopoly ? Seems pretty straightfoward.

**Comment by Maxopoly** [comment]
seems fine

**Comment by mgrandi** [comment]
looks fine

**Pull request merged**
