### PR TITLE
Update to 1.9

### PR DESCRIPTION
**Pull request by Maxopoly**
Merging in all changes from devoteds 1.9 branch

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Worth noting that the fishing loot replacement logic isn't very tested, but it's pretty cool :D

**Comment by Maxopoly** [comment]
It's okay

https://www.youtube.com/watch?v=eUFY8Zw0Bag

**Comment by ProgrammerDan** [comment]
Why did we not merge this in?

**Comment by Maxopoly** [comment]
Because I'm stupid and forgot

**Comment by ProgrammerDan** [comment]
Lol, not stupid. No worries.

**Comment by ProgrammerDan** [comment]
Btw started fixing. I'll have it done a little later, had to take a break.

**Pull request merged**
