### PR TITLE
Persist all the things (except mushrooms)

### PR DESCRIPTION
**Pull request by gipsy-king**
Wrote some nice docs here https://github.com/Civcraft/RealisticBiomes/wiki

Writeup copied from https://forum.civcraft.co/t/realisticbiomes-persisting-thread/484/28?u=gipsyking

Honest to god, I can't reproduce the issue of trees getting cut off at chunk border anymore. I had seen it twice I think. We should just sort it out later, because the fix (if we can call it that, without reproduceability) implies scheduling tasks and waiting for surrounding chunks to load, with potential race conditions or deadlocks.

Here's a write up on what's been done so far:

### Fixed cocoa persistence
Has been tested already, also when clicking with cocoa on a block, it now correctly gives you the growth time in the spot where it would be planted, e.g. hitting a tree.

### A lot of minor fixes and refactors along the way, to compensate a bit with the new crap I added
Growth and fish-drop maps have been joined, their keys are a bit more typesafe now (no more `Object` casting). Untangled some ifs. Fix rabbits in config. `soil_material` may have a data value (e.g. `DIRT:2` for podzol). When hitting block with fishable item and that item's rate is above zero at the location, send message to player about rate.
All of this may of course introduce regression bugs, but it's for the greater good of RB.

### Persist pumpkins and melons
Has been tested, reported OK. Existing melon/pumpkin stems will be made persistent either the next time their fruit is broken (includes piston breaks) or if player right clicks it with stick. If a stem is fully grown, right clicking it with stick will report their fruit growth time. I think I'm being too nice to users :smile:

### Persistent trees
Should work as expected, except:

* Large trees produced from 2x2 array of saplings: the large tree originates from the **northwest** sapling. To get growth time, right click that sapling with a stick, the other sapling won't give any info. There may be bugs when saplings are in an array larger than 2x2 or something similar, althoug so far I have found none.
* Trees that are not able to grow due to obstruction will have their growth time reset and start over, there is no way to get notified though.
* Apparently, birch trees (and maybe others) can grow through some blocks (I've only seen dirt), this is also apparently vanilla behaviour.
* BIG_TREE, TALL_BIRCH, TALL_REDWOOD and JUNGLE_BUSH may spawn, depending on their rate. They are in `config.yml`, and since they don't take their form until they are generated, they're persistence is meaningless and the rest of their config should be based on their normal form, it should not be set to avoid confusion. Think of them like a "chance" like fish drops. Swamp trees only generate in swamp (hi swampdwellers!).
* In theory, we *could* grow [custom trees](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#generateTree(org.bukkit.Location,%20org.bukkit.TreeType,%20org.bukkit.BlockChangeDelegate)) now, for example glowstone strees in the nether or palm trees at beaches or whatever. Ender trees in the end, made out of obsidian with a chest in their crown that holds a few pearls.

### Persisten cactus and sugarcane
Should work as expected. Existing cactus farms will be tracked, they just have to emit a GrowthEvent once per cactus.
Cactus are checked for adjacent blocks on growth, and should drop correctly. I preemtively have added a feature to group item drops *before* they are spawned as item stacks, because I expect a lot of sudden drops from huge farms. This feature can also be used in the future when we want to add some kind of contraption that sucks in drops.

### What now?
I say put it on civtest for a few days, tell players to test EVERY crop/fruit/tree/thing-in-RB for potential regression bugs that may come with so many new features and (necessary) modifications. Then go live and find the real bugs :smile:

### CODE REVIEW

**Comment by drjawa** [comment]
Jawa is pleased.

Pending review. @WildWeazel @ProgrammerDan @rourke750

**Comment by ttk2** [comment]
ok to test

**Comment by ttk2** [comment]
oh, that does not work on this repo. wild?

**Comment by rourke750** [comment]
@gipsy-king Please squash.

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
@ttk2 Nope it isnt set up with this one, let me do that.

**Comment by rourke750** [comment]
ok to test

**Comment by ttk2** [comment]
cool, thanks for getting it working, this is on Civtest now.

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
ok to test

**Comment by erocs** [comment]
ok to test?

**Comment by gipsy-king** [comment]
ok to test!

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
ok to test

**Comment by ttk2** [comment]
testing on this is going well according to dbear, need to rustle up some more testers from the discourse thread.

**Comment by WildWeazel** [comment]
You're a hero, gipsy.

ok to test!

**Comment by ttk2** [comment]
ok to test

**Comment by ttk2** [comment]
ok just put this on the 1.8.7 Civtest

**Pull request merged**
