### PR TITLE
Added two overrides to main plugin class.

### PR DESCRIPTION
**Pull request by plebes**
I added an override to onEnable() and onDisable(), which is standard practice. These functions originate at org.bukkit.plugin.

I know this is minor, but I want to fix anything I see wrong.

### CODE REVIEW

**Comment by ttk2** [comment]
should this go on Civtest or do I want to wait for other minor fixes and do
them all at once?

**Comment by erocs** [comment]
It doesn't need testing.

**Comment by ttk2** [comment]
none of these fixes need testing?

**Comment by erocs** [comment]
Specifically this one doesn't. Wait on other fixes before bothering to move
it live.

**Comment by ttk2** [comment]
putting the version with all todays Minor fixes into testing.

**Pull request merged**
