### PR TITLE
Harvestspam

### PR DESCRIPTION
**Pull request by gipsy-king**
suppress chat spam when harvesting and clicking (fish drop rates)

### CODE REVIEW

**Comment by gipsy-king** [comment]
ok to test

**Comment by gipsy-king** [comment]
@rourke750 does this `ok to test` do anything?

**Comment by ttk2** [comment]
not on this repo, probably not setup.

**Comment by rourke750** [comment]
ok to test

**Comment by gipsy-king** [comment]
ah migo, it must be a jenkins permission thing then.

**Comment by ProgrammerDan** [comment]
So how does this prevent spam? I think I'm missing something. There's no rate limiting?

**Comment by gipsy-king** [comment]
It cancels chat spam if the block being hit is the block that grows from the item. We already had the stuff mapped, e.g. seeds AND wheat item both map to crops block. It works, I tested locally.

**Comment by ttk2** [comment]
so merge and put on Civtest? what about that tree growth problem?

**Comment by gipsy-king** [comment]
The tree thing is something different, I'm gonna open an issue for that.

**Comment by ttk2** [comment]
ok to test

**Comment by ProgrammerDan** [comment]
@gipsy-king Nicely done then, elegant.

**Comment by ttk2** [comment]
should I roll this live?

**Comment by gipsy-king** [comment]
Better put it on civtest for a day, it's nothing urgent anyway.

**Comment by ttk2** [comment]
up on Civtest.

**Comment by ttk2** [comment]
did anyone ever test this? I would love to roll it online

**Comment by gipsy-king** [comment]
Yeah I did at least :heart: also the "unhappy villager effect" when planting in wrong conditions, the same, shoudl be safe to put online.

**Pull request merged**
