### PR TITLE
give player visual feedback if a plant will not grow at placement

### PR DESCRIPTION
**Pull request by gipsy-king**
If the plant growth is zero, then an "angry villager / thundercloud" effect is played near the player. This should give newfriends a hint.

@rourke750 I changed dep from bukkit to spigot as needed for the Effect, I don't know if it that's right with jenkins setup though, care to take a glance?

### CODE REVIEW

**Comment by rourke750** [comment]
That's fine. Very few servers use CraftBukkit anyways.

**Comment by ttk2** [comment]
A text message might also be nice.

**Comment by ttk2** [comment]
but that would be Civmenu's job I think.

**Comment by gipsy-king** [comment]
Could that be too spammy in some scenarios? I can only imagine for example using cacti as deco, wouldn't bother much.

**Comment by ttk2** [comment]
that's why we want Civmenu to handle things like this, because it would keep track of how often the message had been sent in the past and mute it once it happened enough times to assume the player knew. 

Or allow muting of that individual notification and no others. You see why it needs to be a different plugin handling this, too much to throw into RB and then duplicate in every plugin for tutorial messages like this.

**Comment by gipsy-king** [comment]
Yea I'm all in for it.

**Pull request merged**
