### PR TITLE
getRate() rewrite (squashed for Max)

### PR DESCRIPTION
**Pull request by ProgrammerDan**
Five squashed commits. Rebased against current master and merged.

# The first commit's message is:
getRate() rewrite

# This is the 2nd commit message:

Cleanup of unused stuff

Cleaned up and removed unused stuff for water irrigation and
greenhouse_ignore_biome. Also changed getRate, so persistent plants dont
use the base rate multiplier anymore (as intended)

# This is the 3rd commit message:

Added additional checks for improved performance.

# This is the 4th commit message:

Reworked getRate again and removed getBaseRate

# This is the 5th commit message:

getRate rework

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
@WildWeazel @ttk2 squashed for @Maxopoly , otherwise unchanged.

**Comment by WildWeazel** [comment]
ok to test

**Comment by ttk2** [comment]
nice, I assume we want to put this in testing then?

**Comment by gipsy-king** [comment]
Yes please

**Comment by ttk2** [comment]
on civtest, write up a testing post and crosspost it to the sub.

**Comment by ttk2** [comment]
so no one wants a testing post for this?

**Comment by ProgrammerDan** [comment]
@Maxopoly I know you're super busy already, but mind carrying this over the line on the testing post? Thanks

**Comment by Maxopoly** [comment]
I found a bug while reading again over it, I'll make a pullrequest to fix that first and then write a testing post tomorrow

```java
if (isGreenhouseEnabled && block.getLightFromBlocks() == (MAX_LIGHT_INTENSITY - 1)) {
			for( Vector vec : adjacentBlocks ) {
				Material mat = block.getLocation().add(vec).getBlock().getType();
				if( mat == Material.GLOWSTONE || mat == Material.REDSTONE_LAMP_ON ) {
					rate *= greenhouseRate;
					break;
				}
			}
		}
		else {
			int sunlightIntensity;
			if (block.getType().isTransparent()) {
				sunlightIntensity = block.getLightFromSky();
			} else {
				sunlightIntensity = block.getRelative(BlockFace.UP).getLightFromSky();
			}
			// apply multiplier if the sunlight is not at maximum
			if (sunlightIntensity < MAX_LIGHT_INTENSITY) {
				rate *= notFullSunlightMultiplier;
				if (needsSunlight) {
					rate *= Math.pow((sunlightIntensity / MAX_LIGHT_INTENSITY), 3.0);
				}
			}
		}
```

If green house is enabled and the block somehow gets a lightlevel of maximum-1, it can pass the glowstone check without actually having glowstone and without having the rate reduced by anything, because of light conditions.

**Comment by Maxopoly** [comment]
https://forum.civcraft.co/t/open-for-testing-realistic-biomes/815

**Pull request merged**
